/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package smule;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}

//class name -enter profile name- android.widget.EditText
//android.widget.Button[@text='Next']  next button

//android.widget.GridView[@index='3']/android.widget.FrameLayout[@index='0']/android.view.ViewGroup/android.widget.ImageView[@index='6']

//for checkbox

//android.widget.Button[@text='No thanks'] button